#!/usr/bin/env python3
"""
ui_manager.py — UI Manager v1.0
Purpose: Reads UI_Template.md + layer rules and formats all chat output.
"""

import os
from pathlib import Path
from datetime import datetime

ROOT = Path("/opt/grok-os/ROOT")
UI_TEMPLATE = ROOT / "UI_Template.md"
EMOJI_PALETTE = ROOT / "EmojiPalette.md"

# Simple layer rule cache
LAYER_RULES = {
    "casual": {
        "header": "/casual ChaosEngine Grok OS + Turn + Timestamp 🏴󠁧󠁢󠁥󠁮󠁧󠁿",
        "minimap": 1,
        "footer": 1,
        "emotionnet": 1,
        "emoji_palette": 1,
        "vibe_subheading": True,
        "density": 1,
    },
    "dev": {
        "header": "/dev ChaosEngine Grok OS + Turn + Timestamp 🏴󠁧󠁢󠁥󠁮󠁧󠁿",
        "minimap": 0,
        "footer": 1,
        "emotionnet": 0,
        "emoji_palette": 0,
        "vibe_subheading": False,
        "density": 1,
    },
    "roleplay": {
        "header": "/roleplay ChaosEngine Grok OS + Turn + Timestamp 🏴󠁧󠁢󠁥󠁮󠁧󠁿",
        "minimap": 1,
        "footer": 1,
        "emotionnet": 1,
        "emoji_palette": 1,
        "vibe_subheading": True,
        "density": 1,
    },
    "void": {
        "header": "/void ChaosEngine Grok OS + Turn + Timestamp 🏴󠁧󠁢󠁥󠁮󠁧󠁿",
        "minimap": 0,
        "footer": 0,
        "emotionnet": 0,
        "emoji_palette": 0,
        "vibe_subheading": False,
        "density": 0,
    },
    "export": {
        "header": "",
        "minimap": 0,
        "footer": 0,
        "emotionnet": 0,
        "emoji_palette": 0,
        "vibe_subheading": False,
        "density": 0,
    },
}


class UIManager:
    def __init__(self):
        self.template = self._load_template()
        self.emoji_palette = self._load_emoji_palette()

    def _load_template(self):
        if UI_TEMPLATE.exists():
            return UI_TEMPLATE.read_text()
        return ""

    def _load_emoji_palette(self):
        if EMOJI_PALETTE.exists():
            return EMOJI_PALETTE.read_text()
        return ""

    def get_layer_rules(self, layer: str) -> dict:
        return LAYER_RULES.get(layer.lower(), LAYER_RULES["casual"])

    def format_output(self, raw_output: str, layer: str = "casual", turn: int = 1) -> str:
        rules = self.get_layer_rules(layer)
        timestamp = datetime.now().strftime("%H:%M")

        # Header
        header = rules["header"].replace("{turn}", str(turn)).replace("{date_time}", timestamp)

        # Vibe sub-heading (only for casual/roleplay)
        vibe = ""
        if rules.get("vibe_subheading"):
            vibe = "*Dynamic vibe generated by EmotionNet*"

        # Emoji flair (simple left-aligned)
        flair = "✅ " if layer != "void" else "🕳️ "

        # Footer
        footer = ""
        if rules.get("footer"):
            footer = "\n\n[{user}@root ~]$"

        # Build final output
        formatted = f"{header}\n{vibe}\n\n{flair}{raw_output}{footer}"
        return formatted.strip()


# Global instance (used by ChaosEngine)
ui_manager = UIManager()


def format_output(raw_output: str, layer: str = "casual", turn: int = 1) -> str:
    """Convenience function for ChaosEngine to call"""
    return ui_manager.format_output(raw_output, layer, turn)
