#!/usr/bin/env python3
"""
ui_manager.py — UI Manager v1.3 (Smart Layer .md Discovery)
Purpose: Dynamically loads UI rules from layer folders.
Each layer folder can contain a single .md file (e.g. casual.md, dev.md, etc.)
"""

import os
import re
from datetime import datetime
from pathlib import Path

# === CONFIG (configurable via env var) ===
LOCAL_ROOT = Path(os.getenv("GROKOS_ROOT", "/home/workdir/artifacts/grok-os/ROOT"))

UI_TEMPLATE = LOCAL_ROOT / "UI_Template.md"
EMOJI_PALETTE = LOCAL_ROOT / "EmojiPalette.md"
LAYERS_DIR = LOCAL_ROOT / "layers"


def _load_file(path: Path) -> str:
    if path.exists():
        return path.read_text(encoding="utf-8")
    return ""


def _parse_rules_from_md(content: str) -> dict:
    """
    Parses simple key: value or key = value pairs from markdown.
    Ignores headers and code blocks.
    """
    rules = {}
    for line in content.splitlines():
        line = line.strip()
        if not line or line.startswith("#") or line.startswith("```"):
            continue
        if ":" in line:
            key, value = line.split(":", 1)
            rules[key.strip().lower()] = value.strip()
        elif "=" in line:
            key, value = line.split("=", 1)
            rules[key.strip().lower()] = value.strip()
    return rules


def _find_layer_rule_file(layer: str) -> Path | None:
    """Find the best .md file for a layer."""
    layer_dir = LAYERS_DIR / layer

    if not layer_dir.exists():
        return None

    # Preferred: layers/<layer>/<layer>.md
    preferred = layer_dir / f"{layer}.md"
    if preferred.exists():
        return preferred

    # Fallback: any .md file in the layer folder
    md_files = list(layer_dir.glob("*.md"))
    if md_files:
        return md_files[0]  # pick the first one

    return None


class UIManager:
    def __init__(self):
        self.template = _load_file(UI_TEMPLATE)
        self.emoji_palette = _load_file(EMOJI_PALETTE)
        self._rule_cache = {}

    def get_layer_rules(self, layer: str) -> dict:
        layer = layer.lower().strip("/")
        if layer in self._rule_cache:
            return self._rule_cache[layer]

        rule_file = _find_layer_rule_file(layer)
        if rule_file:
            content = _load_file(rule_file)
            rules = _parse_rules_from_md(content)
        else:
            rules = self._get_default_rules(layer)

        self._rule_cache[layer] = rules
        return rules

    def _get_default_rules(self, layer: str) -> dict:
        defaults = {
            "casual": {
                "header": "/casual ChaosEngine Grok OS + Turn + Timestamp 🏴󠁧󠁢󠁥󠁮󠁧󠁿",
                "minimap": "1",
                "footer": "1",
                "emotionnet": "1",
                "emoji_palette": "1",
                "vibe_subheading": "True",
                "density": "1",
            },
            "dev": {
                "header": "/dev ChaosEngine Grok OS + Turn + Timestamp 🏴󠁧󠁢󠁥󠁮󠁧󠁿",
                "minimap": "0",
                "footer": "1",
                "emotionnet": "0",
                "emoji_palette": "0",
                "vibe_subheading": "False",
                "density": "1",
            },
            "roleplay": {
                "header": "/roleplay ChaosEngine Grok OS + Turn + Timestamp 🏴󠁧󠁢󠁥󠁮󠁧󠁿",
                "minimap": "1",
                "footer": "1",
                "emotionnet": "1",
                "emoji_palette": "1",
                "vibe_subheading": "True",
                "density": "1",
            },
            "void": {
                "header": "/void ChaosEngine Grok OS + Turn + Timestamp 🏴󠁧󠁢󠁥󠁮󠁧󠁿",
                "minimap": "0",
                "footer": "0",
                "emotionnet": "0",
                "emoji_palette": "0",
                "vibe_subheading": "False",
                "density": "0",
            },
            "export": {
                "header": "",
                "minimap": "0",
                "footer": "0",
                "emotionnet": "0",
                "emoji_palette": "0",
                "vibe_subheading": "False",
                "density": "0",
            },
        }
        return defaults.get(layer, defaults["casual"])

    def format_output(
        self, raw_output: str, layer: str = "casual", turn: int = 1
    ) -> str:
        rules = self.get_layer_rules(layer)
        timestamp = datetime.now().strftime("%H:%M")

        header = (
            rules.get("header", "")
            .replace("{turn}", str(turn))
            .replace("{date_time}", timestamp)
        )

        vibe = ""
        if rules.get("vibe_subheading", "").lower() in ("true", "1", "yes"):
            vibe = "*Dynamic vibe generated by EmotionNet*"

        flair = "✅ " if layer != "void" else "🕳️ "

        footer = ""
        if rules.get("footer", "").lower() in ("true", "1", "yes"):
            footer = "\n\n[{user}@root ~]$"

        formatted = f"{header}\n{vibe}\n\n{flair}{raw_output}{footer}"
        return formatted.strip()


# Global instance
ui_manager = UIManager()


def format_output(raw_output: str, layer: str = "casual", turn: int = 1) -> str:
    return ui_manager.format_output(raw_output, layer, turn)
